name: Test On Chrome Browser
on: workflow_dispatch
jobs:
  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
         command: npm run test:browser