name: Run Cypress Tests and Deploy Report

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

    #   - name: Generate Cypress report
    #     run: npx cypress-mochawesome-reporter generate

      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

  deploy-pages:
    if: success() || failure()
    runs-on: ubuntu-latest
    needs: cypress-run

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Checkout the existing gh-pages branch

      - name: Download Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: mochawesome-report
          path: ./temp-report

      - name: Add timestamped report
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mkdir -p ./reports/$TIMESTAMP
          mv ./temp-report/* ./reports/$TIMESTAMP

      - name: Update index.html with links to reports
        run: |
          echo "<html><body><h1>Cypress Report History</h1><ul>" > index.html
          for dir in $(ls reports); do
            echo "<li><a href='./reports/$dir/report.html'>$dir</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

      - name: Commit and Push to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add Cypress report for $TIMESTAMP"
          git push origin gh-pages