name: Cypress Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Checkout gh-pages branch
        if: always()
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          mkdir -p reports

      - name: Determine next report number
        id: report_number
        run: |
          number=$(ls reports | grep -Eo 'report-[0-9]+' | sed 's/report-//' | sort -n | tail -n 1)
          if [ -z "$number" ]; then
            number=0
          fi
          echo "NEXT_REPORT_NUMBER=$((number + 1))" >> $GITHUB_ENV

      - name: Save report with ordinal number
        run: |
          mkdir -p "reports/report-${{ env.NEXT_REPORT_NUMBER }}"
          cp -r cypress/reports/* "reports/report-${{ env.NEXT_REPORT_NUMBER }}"

      - name: Limit number of historical reports
        run: |
          max_reports=5  # Set the number of reports to keep
          report_dirs=$(ls -d reports/report-* | sort -V)
          current_count=$(echo "$report_dirs" | wc -l)
          if [ "$current_count" -gt "$max_reports" ]; then
            reports_to_delete=$(echo "$report_dirs" | head -n $((current_count-max_reports)))
            echo "$reports_to_delete" | xargs rm -rf
          fi

      - name: Push reports to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports
          git commit -m "Add report ${{ env.NEXT_REPORT_NUMBER }}"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports