name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

  deploy-pages:
    runs-on: ubuntu-latest
    needs: cypress-run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: mochawesome-report
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true  # This option helps in creating the gh-pages branch if it doesn't exist